apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: seldon
type: Opaque
stringData:
  TEST_MOCK_SECRET: Test mock secret value is here


---

apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-mock-model
  namespace: seldon
spec:
  predictors:
  - name: default
    replicas: 1
    componentSpecs:
    - spec:
        containers:
        - image: rafalskolasinski/mock-model:latest
          imagePullPolicy: IfNotPresent
          name: mock-model
          env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
          envFrom:
          - secretRef:
              name: test-secret
    graph:
      type: MODEL
      name: mock-model
